/*import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
*/

//import Header from "@components/Footer";
//import Footer from "@components/Header";
import Head from "next/head";
import "../styles/globals.css";
import { Montserrat } from 'next/font/google';

const montserrat = Montserrat({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'], // Supported language sets
  display: 'swap', // Rendering optimization
});

import Nav from "../components/Nav";

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={montserrat.className}>
      <Head>
        <title>TachLab</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Nav />
        {children}
      </body>
    </html>
  )
}